name: Demo Workflow
on: [workflow_dispatch]
jobs: 
  print: 
    runs-on: macos-15-large
    steps:
      - name: Print to console
        run: echo Hello GH Actions!
      - name: Print a few lines
        run: |
          echo First line!
          echo Second line!
